/* File: fingerprintmodule.c
 * This file is auto-generated with f2py (version:1.24.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Feb 28 23:00:58 2026
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fingerprint_error;
static PyObject *fingerprint_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(fingerprint_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#define CHECKARRAY(check,tcheck,name) \
    if (!(check)) {\
        PyErr_SetString(fingerprint_error,"("tcheck") failed for "name);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)

/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = fingerprint_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fingerprint_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = fingerprint_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(fingerprint_and_derivatives,FINGERPRINT_AND_DERIVATIVES)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*);
extern void F_FUNC_US(atoms_sphere,ATOMS_SPHERE)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,double*);
extern void F_FUNC(crtovrlp,CRTOVRLP)(int*,double*,double*,double*,double*,int*,int*,double*);
extern void F_FUNC(multamp,MULTAMP)(int*,double*,double*,int*,int*,int*,double*);
extern void F_FUNC(diagonalizeMatrix,DIAGONALIZEMATRIX)(int*,double*,double*);
extern void F_FUNC(sym2rcov,SYM2RCOV)(string,double*,size_t);
extern void F_FUNC(xyz2ovrlpdr,XYZ2OVRLPDR)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,int*,int*,double*,double*);
extern void F_FUNC(cite,CITE)(void);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************ fingerprint_and_derivatives ************************/
static char doc_f2py_rout_fingerprint_fingerprint_and_derivatives[] = "\
fingerprint_and_derivatives(nat_sphere_max,ns,np,width_cutoff,alat,rxyz,rcov,fp,dfp,[nat])\n\nWrapper for ``fingerprint_and_derivatives``.\
\n\nParameters\n----------\n"
"nat_sphere_max : input int\n"
"ns : input int\n"
"np : input int\n"
"width_cutoff : input float\n"
"alat : input rank-2 array('d') with bounds (3,3)\n"
"rxyz : input rank-2 array('d') with bounds (3,nat)\n"
"rcov : input rank-1 array('d') with bounds (nat)\n"
"fp : input rank-1 array('d') with bounds (3 * nat_sphere_max * np + nat_sphere_max * ns)\n"
"dfp : input rank-3 array('d') with bounds (3 * nat_sphere_max * np + nat_sphere_max * ns,3,nat)\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(rxyz, 1)";
/* extern void F_FUNC_US(fingerprint_and_derivatives,FINGERPRINT_AND_DERIVATIVES)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_fingerprint_fingerprint_and_derivatives(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nat = 0;
    PyObject *nat_capi = Py_None;
    int nat_sphere_max = 0;
    PyObject *nat_sphere_max_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double width_cutoff = 0;
    PyObject *width_cutoff_capi = Py_None;
    double *alat = NULL;
    npy_intp alat_Dims[2] = {-1, -1};
    const int alat_Rank = 2;
    PyArrayObject *capi_alat_as_array = NULL;
    int capi_alat_intent = 0;
    PyObject *alat_capi = Py_None;
    double *rxyz = NULL;
    npy_intp rxyz_Dims[2] = {-1, -1};
    const int rxyz_Rank = 2;
    PyArrayObject *capi_rxyz_as_array = NULL;
    int capi_rxyz_intent = 0;
    PyObject *rxyz_capi = Py_None;
    double *rcov = NULL;
    npy_intp rcov_Dims[1] = {-1};
    const int rcov_Rank = 1;
    PyArrayObject *capi_rcov_as_array = NULL;
    int capi_rcov_intent = 0;
    PyObject *rcov_capi = Py_None;
    double *fp = NULL;
    npy_intp fp_Dims[1] = {-1};
    const int fp_Rank = 1;
    PyArrayObject *capi_fp_as_array = NULL;
    int capi_fp_intent = 0;
    PyObject *fp_capi = Py_None;
    double *dfp = NULL;
    npy_intp dfp_Dims[3] = {-1, -1, -1};
    const int dfp_Rank = 3;
    PyArrayObject *capi_dfp_as_array = NULL;
    int capi_dfp_intent = 0;
    PyObject *dfp_capi = Py_None;
    static char *capi_kwlist[] = {"nat_sphere_max","ns","np","width_cutoff","alat","rxyz","rcov","fp","dfp","nat",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOO|O:fingerprint.fingerprint_and_derivatives",\
        capi_kwlist,&nat_sphere_max_capi,&ns_capi,&np_capi,&width_cutoff_capi,&alat_capi,&rxyz_capi,&rcov_capi,&fp_capi,&dfp_capi,&nat_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"fingerprint.fingerprint_and_derivatives() 2nd argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
        f2py_success = int_from_pyobj(&np,np_capi,"fingerprint.fingerprint_and_derivatives() 3rd argument (np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nat_sphere_max */
        f2py_success = int_from_pyobj(&nat_sphere_max,nat_sphere_max_capi,"fingerprint.fingerprint_and_derivatives() 1st argument (nat_sphere_max) can't be converted to int");
    if (f2py_success) {
    /* Processing variable width_cutoff */
        f2py_success = double_from_pyobj(&width_cutoff,width_cutoff_capi,"fingerprint.fingerprint_and_derivatives() 4th argument (width_cutoff) can't be converted to double");
    if (f2py_success) {
    /* Processing variable rxyz */
    rxyz_Dims[0]=3;
    capi_rxyz_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.fingerprint_and_derivatives: failed to create array from the 6th argument `rxyz`";
    capi_rxyz_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rxyz_Dims,rxyz_Rank,  capi_rxyz_intent,rxyz_capi,capi_errmess);
    if (capi_rxyz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rxyz = (double *)(PyArray_DATA(capi_rxyz_as_array));

    /* Processing variable alat */
    alat_Dims[0]=3,alat_Dims[1]=3;
    capi_alat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.fingerprint_and_derivatives: failed to create array from the 5th argument `alat`";
    capi_alat_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alat_Dims,alat_Rank,  capi_alat_intent,alat_capi,capi_errmess);
    if (capi_alat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alat = (double *)(PyArray_DATA(capi_alat_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(rxyz, 1); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"fingerprint.fingerprint_and_derivatives() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rxyz, 1) == nat,"shape(rxyz, 1) == nat","1st keyword nat","fingerprint_and_derivatives:nat=%d",nat) {
    /* Processing variable rcov */
    rcov_Dims[0]=nat;
    capi_rcov_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.fingerprint_and_derivatives: failed to create array from the 7th argument `rcov`";
    capi_rcov_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rcov_Dims,rcov_Rank,  capi_rcov_intent,rcov_capi,capi_errmess);
    if (capi_rcov_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rcov = (double *)(PyArray_DATA(capi_rcov_as_array));

    /* Processing variable fp */
    fp_Dims[0]=3 * nat_sphere_max * np + nat_sphere_max * ns;
    capi_fp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.fingerprint_and_derivatives: failed to create array from the 8th argument `fp`";
    capi_fp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,fp_Dims,fp_Rank,  capi_fp_intent,fp_capi,capi_errmess);
    if (capi_fp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        fp = (double *)(PyArray_DATA(capi_fp_as_array));

    CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","8th argument fp") {
    CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","8th argument fp") {
    CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","8th argument fp") {
    /* Processing variable dfp */
    dfp_Dims[0]=3 * nat_sphere_max * np + nat_sphere_max * ns,dfp_Dims[1]=3,dfp_Dims[2]=nat;
    capi_dfp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.fingerprint_and_derivatives: failed to create array from the 9th argument `dfp`";
    capi_dfp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dfp_Dims,dfp_Rank,  capi_dfp_intent,dfp_capi,capi_errmess);
    if (capi_dfp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dfp = (double *)(PyArray_DATA(capi_dfp_as_array));

    CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","9th argument dfp") {
    CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","9th argument dfp") {
    CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns,"shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns","9th argument dfp") {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nat,&nat_sphere_max,&ns,&np,&width_cutoff,alat,rxyz,rcov,fp,dfp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    } /*CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    } /*CHECKARRAY(shape(dfp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    if((PyObject *)capi_dfp_as_array!=dfp_capi) {
        Py_XDECREF(capi_dfp_as_array); }
    }  /* if (capi_dfp_as_array == NULL) ... else of dfp */
    /* End of cleaning variable dfp */
    } /*CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    } /*CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    } /*CHECKARRAY(shape(fp, 0) == 3 * nat_sphere_max * np + nat_sphere_max * ns)*/
    if((PyObject *)capi_fp_as_array!=fp_capi) {
        Py_XDECREF(capi_fp_as_array); }
    }  /* if (capi_fp_as_array == NULL) ... else of fp */
    /* End of cleaning variable fp */
    if((PyObject *)capi_rcov_as_array!=rcov_capi) {
        Py_XDECREF(capi_rcov_as_array); }
    }  /* if (capi_rcov_as_array == NULL) ... else of rcov */
    /* End of cleaning variable rcov */
    } /*CHECKSCALAR(shape(rxyz, 1) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_alat_as_array!=alat_capi) {
        Py_XDECREF(capi_alat_as_array); }
    }  /* if (capi_alat_as_array == NULL) ... else of alat */
    /* End of cleaning variable alat */
    if((PyObject *)capi_rxyz_as_array!=rxyz_capi) {
        Py_XDECREF(capi_rxyz_as_array); }
    }  /* if (capi_rxyz_as_array == NULL) ... else of rxyz */
    /* End of cleaning variable rxyz */
    } /*if (f2py_success) of width_cutoff*/
    /* End of cleaning variable width_cutoff */
    } /*if (f2py_success) of nat_sphere_max*/
    /* End of cleaning variable nat_sphere_max */
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************* end of fingerprint_and_derivatives *********************/

/******************************** atoms_sphere ********************************/
static char doc_f2py_rout_fingerprint_atoms_sphere[] = "\
atoms_sphere(width_cutoff,nex_cutoff,lat,llat,ixyzmax,nat_sphere,alat,rxyz,rxyz_sphere,rcov,rcov_sphere,indat,amplitude,deramplitude,[nat,natx_sphere])\n\nWrapper for ``atoms_sphere``.\
\n\nParameters\n----------\n"
"width_cutoff : input float\n"
"nex_cutoff : input int\n"
"lat : input int\n"
"llat : input int\n"
"ixyzmax : input int\n"
"nat_sphere : input int\n"
"alat : input rank-2 array('d') with bounds (3,3)\n"
"rxyz : input rank-2 array('d') with bounds (3,nat)\n"
"rxyz_sphere : input rank-2 array('d') with bounds (3,natx_sphere)\n"
"rcov : input rank-1 array('d') with bounds (nat)\n"
"rcov_sphere : input rank-1 array('d') with bounds (natx_sphere)\n"
"indat : input rank-1 array('i') with bounds (natx_sphere)\n"
"amplitude : input rank-1 array('d') with bounds (natx_sphere)\n"
"deramplitude : input rank-1 array('d') with bounds (natx_sphere)\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(rxyz, 1)\n"
"natx_sphere : input int, optional\n    Default: shape(rxyz_sphere, 1)";
/* extern void F_FUNC_US(atoms_sphere,ATOMS_SPHERE)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,double*); */
static PyObject *f2py_rout_fingerprint_atoms_sphere(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double width_cutoff = 0;
    PyObject *width_cutoff_capi = Py_None;
    int nex_cutoff = 0;
    PyObject *nex_cutoff_capi = Py_None;
    int lat = 0;
    PyObject *lat_capi = Py_None;
    int llat = 0;
    PyObject *llat_capi = Py_None;
    int ixyzmax = 0;
    PyObject *ixyzmax_capi = Py_None;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    int natx_sphere = 0;
    PyObject *natx_sphere_capi = Py_None;
    int nat_sphere = 0;
    PyObject *nat_sphere_capi = Py_None;
    double *alat = NULL;
    npy_intp alat_Dims[2] = {-1, -1};
    const int alat_Rank = 2;
    PyArrayObject *capi_alat_as_array = NULL;
    int capi_alat_intent = 0;
    PyObject *alat_capi = Py_None;
    double *rxyz = NULL;
    npy_intp rxyz_Dims[2] = {-1, -1};
    const int rxyz_Rank = 2;
    PyArrayObject *capi_rxyz_as_array = NULL;
    int capi_rxyz_intent = 0;
    PyObject *rxyz_capi = Py_None;
    double *rxyz_sphere = NULL;
    npy_intp rxyz_sphere_Dims[2] = {-1, -1};
    const int rxyz_sphere_Rank = 2;
    PyArrayObject *capi_rxyz_sphere_as_array = NULL;
    int capi_rxyz_sphere_intent = 0;
    PyObject *rxyz_sphere_capi = Py_None;
    double *rcov = NULL;
    npy_intp rcov_Dims[1] = {-1};
    const int rcov_Rank = 1;
    PyArrayObject *capi_rcov_as_array = NULL;
    int capi_rcov_intent = 0;
    PyObject *rcov_capi = Py_None;
    double *rcov_sphere = NULL;
    npy_intp rcov_sphere_Dims[1] = {-1};
    const int rcov_sphere_Rank = 1;
    PyArrayObject *capi_rcov_sphere_as_array = NULL;
    int capi_rcov_sphere_intent = 0;
    PyObject *rcov_sphere_capi = Py_None;
    int *indat = NULL;
    npy_intp indat_Dims[1] = {-1};
    const int indat_Rank = 1;
    PyArrayObject *capi_indat_as_array = NULL;
    int capi_indat_intent = 0;
    PyObject *indat_capi = Py_None;
    double *amplitude = NULL;
    npy_intp amplitude_Dims[1] = {-1};
    const int amplitude_Rank = 1;
    PyArrayObject *capi_amplitude_as_array = NULL;
    int capi_amplitude_intent = 0;
    PyObject *amplitude_capi = Py_None;
    double *deramplitude = NULL;
    npy_intp deramplitude_Dims[1] = {-1};
    const int deramplitude_Rank = 1;
    PyArrayObject *capi_deramplitude_as_array = NULL;
    int capi_deramplitude_intent = 0;
    PyObject *deramplitude_capi = Py_None;
    static char *capi_kwlist[] = {"width_cutoff","nex_cutoff","lat","llat","ixyzmax","nat_sphere","alat","rxyz","rxyz_sphere","rcov","rcov_sphere","indat","amplitude","deramplitude","nat","natx_sphere",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOO|OO:fingerprint.atoms_sphere",\
        capi_kwlist,&width_cutoff_capi,&nex_cutoff_capi,&lat_capi,&llat_capi,&ixyzmax_capi,&nat_sphere_capi,&alat_capi,&rxyz_capi,&rxyz_sphere_capi,&rcov_capi,&rcov_sphere_capi,&indat_capi,&amplitude_capi,&deramplitude_capi,&nat_capi,&natx_sphere_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable nex_cutoff */
        f2py_success = int_from_pyobj(&nex_cutoff,nex_cutoff_capi,"fingerprint.atoms_sphere() 2nd argument (nex_cutoff) can't be converted to int");
    if (f2py_success) {
    /* Processing variable lat */
        f2py_success = int_from_pyobj(&lat,lat_capi,"fingerprint.atoms_sphere() 3rd argument (lat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ixyzmax */
        f2py_success = int_from_pyobj(&ixyzmax,ixyzmax_capi,"fingerprint.atoms_sphere() 5th argument (ixyzmax) can't be converted to int");
    if (f2py_success) {
    /* Processing variable llat */
        f2py_success = int_from_pyobj(&llat,llat_capi,"fingerprint.atoms_sphere() 4th argument (llat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nat_sphere */
        f2py_success = int_from_pyobj(&nat_sphere,nat_sphere_capi,"fingerprint.atoms_sphere() 6th argument (nat_sphere) can't be converted to int");
    if (f2py_success) {
    /* Processing variable width_cutoff */
        f2py_success = double_from_pyobj(&width_cutoff,width_cutoff_capi,"fingerprint.atoms_sphere() 1st argument (width_cutoff) can't be converted to double");
    if (f2py_success) {
    /* Processing variable rxyz_sphere */
    rxyz_sphere_Dims[0]=3;
    capi_rxyz_sphere_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 9th argument `rxyz_sphere`";
    capi_rxyz_sphere_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rxyz_sphere_Dims,rxyz_sphere_Rank,  capi_rxyz_sphere_intent,rxyz_sphere_capi,capi_errmess);
    if (capi_rxyz_sphere_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rxyz_sphere = (double *)(PyArray_DATA(capi_rxyz_sphere_as_array));

    /* Processing variable rxyz */
    rxyz_Dims[0]=3;
    capi_rxyz_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 8th argument `rxyz`";
    capi_rxyz_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rxyz_Dims,rxyz_Rank,  capi_rxyz_intent,rxyz_capi,capi_errmess);
    if (capi_rxyz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rxyz = (double *)(PyArray_DATA(capi_rxyz_as_array));

    /* Processing variable alat */
    alat_Dims[0]=3,alat_Dims[1]=3;
    capi_alat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 7th argument `alat`";
    capi_alat_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alat_Dims,alat_Rank,  capi_alat_intent,alat_capi,capi_errmess);
    if (capi_alat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alat = (double *)(PyArray_DATA(capi_alat_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(rxyz, 1); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"fingerprint.atoms_sphere() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rxyz, 1) == nat,"shape(rxyz, 1) == nat","1st keyword nat","atoms_sphere:nat=%d",nat) {
    /* Processing variable natx_sphere */
    if (natx_sphere_capi == Py_None) natx_sphere = shape(rxyz_sphere, 1); else
        f2py_success = int_from_pyobj(&natx_sphere,natx_sphere_capi,"fingerprint.atoms_sphere() 2nd keyword (natx_sphere) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rxyz_sphere, 1) == natx_sphere,"shape(rxyz_sphere, 1) == natx_sphere","2nd keyword natx_sphere","atoms_sphere:natx_sphere=%d",natx_sphere) {
    /* Processing variable rcov_sphere */
    rcov_sphere_Dims[0]=natx_sphere;
    capi_rcov_sphere_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 11st argument `rcov_sphere`";
    capi_rcov_sphere_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rcov_sphere_Dims,rcov_sphere_Rank,  capi_rcov_sphere_intent,rcov_sphere_capi,capi_errmess);
    if (capi_rcov_sphere_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rcov_sphere = (double *)(PyArray_DATA(capi_rcov_sphere_as_array));

    /* Processing variable amplitude */
    amplitude_Dims[0]=natx_sphere;
    capi_amplitude_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 13rd argument `amplitude`";
    capi_amplitude_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,amplitude_Dims,amplitude_Rank,  capi_amplitude_intent,amplitude_capi,capi_errmess);
    if (capi_amplitude_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        amplitude = (double *)(PyArray_DATA(capi_amplitude_as_array));

    /* Processing variable deramplitude */
    deramplitude_Dims[0]=natx_sphere;
    capi_deramplitude_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 14th argument `deramplitude`";
    capi_deramplitude_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,deramplitude_Dims,deramplitude_Rank,  capi_deramplitude_intent,deramplitude_capi,capi_errmess);
    if (capi_deramplitude_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        deramplitude = (double *)(PyArray_DATA(capi_deramplitude_as_array));

    /* Processing variable rcov */
    rcov_Dims[0]=nat;
    capi_rcov_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 10th argument `rcov`";
    capi_rcov_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rcov_Dims,rcov_Rank,  capi_rcov_intent,rcov_capi,capi_errmess);
    if (capi_rcov_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rcov = (double *)(PyArray_DATA(capi_rcov_as_array));

    /* Processing variable indat */
    indat_Dims[0]=natx_sphere;
    capi_indat_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.atoms_sphere: failed to create array from the 12nd argument `indat`";
    capi_indat_as_array = ndarray_from_pyobj(  NPY_INT,1,indat_Dims,indat_Rank,  capi_indat_intent,indat_capi,capi_errmess);
    if (capi_indat_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        indat = (int *)(PyArray_DATA(capi_indat_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&width_cutoff,&nex_cutoff,&lat,&llat,&ixyzmax,&nat,&natx_sphere,&nat_sphere,alat,rxyz,rxyz_sphere,rcov,rcov_sphere,indat,amplitude,deramplitude);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_indat_as_array!=indat_capi) {
        Py_XDECREF(capi_indat_as_array); }
    }  /* if (capi_indat_as_array == NULL) ... else of indat */
    /* End of cleaning variable indat */
    if((PyObject *)capi_rcov_as_array!=rcov_capi) {
        Py_XDECREF(capi_rcov_as_array); }
    }  /* if (capi_rcov_as_array == NULL) ... else of rcov */
    /* End of cleaning variable rcov */
    if((PyObject *)capi_deramplitude_as_array!=deramplitude_capi) {
        Py_XDECREF(capi_deramplitude_as_array); }
    }  /* if (capi_deramplitude_as_array == NULL) ... else of deramplitude */
    /* End of cleaning variable deramplitude */
    if((PyObject *)capi_amplitude_as_array!=amplitude_capi) {
        Py_XDECREF(capi_amplitude_as_array); }
    }  /* if (capi_amplitude_as_array == NULL) ... else of amplitude */
    /* End of cleaning variable amplitude */
    if((PyObject *)capi_rcov_sphere_as_array!=rcov_sphere_capi) {
        Py_XDECREF(capi_rcov_sphere_as_array); }
    }  /* if (capi_rcov_sphere_as_array == NULL) ... else of rcov_sphere */
    /* End of cleaning variable rcov_sphere */
    } /*CHECKSCALAR(shape(rxyz_sphere, 1) == natx_sphere)*/
    } /*if (f2py_success) of natx_sphere*/
    /* End of cleaning variable natx_sphere */
    } /*CHECKSCALAR(shape(rxyz, 1) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_alat_as_array!=alat_capi) {
        Py_XDECREF(capi_alat_as_array); }
    }  /* if (capi_alat_as_array == NULL) ... else of alat */
    /* End of cleaning variable alat */
    if((PyObject *)capi_rxyz_as_array!=rxyz_capi) {
        Py_XDECREF(capi_rxyz_as_array); }
    }  /* if (capi_rxyz_as_array == NULL) ... else of rxyz */
    /* End of cleaning variable rxyz */
    if((PyObject *)capi_rxyz_sphere_as_array!=rxyz_sphere_capi) {
        Py_XDECREF(capi_rxyz_sphere_as_array); }
    }  /* if (capi_rxyz_sphere_as_array == NULL) ... else of rxyz_sphere */
    /* End of cleaning variable rxyz_sphere */
    } /*if (f2py_success) of width_cutoff*/
    /* End of cleaning variable width_cutoff */
    } /*if (f2py_success) of nat_sphere*/
    /* End of cleaning variable nat_sphere */
    } /*if (f2py_success) of llat*/
    /* End of cleaning variable llat */
    } /*if (f2py_success) of ixyzmax*/
    /* End of cleaning variable ixyzmax */
    } /*if (f2py_success) of lat*/
    /* End of cleaning variable lat */
    } /*if (f2py_success) of nex_cutoff*/
    /* End of cleaning variable nex_cutoff */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of atoms_sphere ****************************/

/********************************** crtovrlp **********************************/
static char doc_f2py_rout_fingerprint_crtovrlp[] = "\
crtovrlp(rxyz,alpha,cs,cp,ns,np,ovrlp,[nat])\n\nWrapper for ``crtovrlp``.\
\n\nParameters\n----------\n"
"rxyz : input rank-2 array('d') with bounds (3,nat)\n"
"alpha : input rank-1 array('d') with bounds (nat)\n"
"cs : input rank-1 array('d') with bounds (10)\n"
"cp : input rank-1 array('d') with bounds (10)\n"
"ns : input int\n"
"np : input int\n"
"ovrlp : input rank-2 array('d') with bounds (3 * nat * np + nat * ns,3 * nat * np + nat * ns)\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(rxyz, 1)";
/* extern void F_FUNC(crtovrlp,CRTOVRLP)(int*,double*,double*,double*,double*,int*,int*,double*); */
static PyObject *f2py_rout_fingerprint_crtovrlp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,double*,int*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nat = 0;
    PyObject *nat_capi = Py_None;
    double *rxyz = NULL;
    npy_intp rxyz_Dims[2] = {-1, -1};
    const int rxyz_Rank = 2;
    PyArrayObject *capi_rxyz_as_array = NULL;
    int capi_rxyz_intent = 0;
    PyObject *rxyz_capi = Py_None;
    double *alpha = NULL;
    npy_intp alpha_Dims[1] = {-1};
    const int alpha_Rank = 1;
    PyArrayObject *capi_alpha_as_array = NULL;
    int capi_alpha_intent = 0;
    PyObject *alpha_capi = Py_None;
    double *cs = NULL;
    npy_intp cs_Dims[1] = {-1};
    const int cs_Rank = 1;
    PyArrayObject *capi_cs_as_array = NULL;
    int capi_cs_intent = 0;
    PyObject *cs_capi = Py_None;
    double *cp = NULL;
    npy_intp cp_Dims[1] = {-1};
    const int cp_Rank = 1;
    PyArrayObject *capi_cp_as_array = NULL;
    int capi_cp_intent = 0;
    PyObject *cp_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double *ovrlp = NULL;
    npy_intp ovrlp_Dims[2] = {-1, -1};
    const int ovrlp_Rank = 2;
    PyArrayObject *capi_ovrlp_as_array = NULL;
    int capi_ovrlp_intent = 0;
    PyObject *ovrlp_capi = Py_None;
    static char *capi_kwlist[] = {"rxyz","alpha","cs","cp","ns","np","ovrlp","nat",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOO|O:fingerprint.crtovrlp",\
        capi_kwlist,&rxyz_capi,&alpha_capi,&cs_capi,&cp_capi,&ns_capi,&np_capi,&ovrlp_capi,&nat_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"fingerprint.crtovrlp() 5th argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
        f2py_success = int_from_pyobj(&np,np_capi,"fingerprint.crtovrlp() 6th argument (np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable rxyz */
    rxyz_Dims[0]=3;
    capi_rxyz_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.crtovrlp: failed to create array from the 1st argument `rxyz`";
    capi_rxyz_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rxyz_Dims,rxyz_Rank,  capi_rxyz_intent,rxyz_capi,capi_errmess);
    if (capi_rxyz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rxyz = (double *)(PyArray_DATA(capi_rxyz_as_array));

    /* Processing variable cs */
    cs_Dims[0]=10;
    capi_cs_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.crtovrlp: failed to create array from the 3rd argument `cs`";
    capi_cs_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cs_Dims,cs_Rank,  capi_cs_intent,cs_capi,capi_errmess);
    if (capi_cs_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cs = (double *)(PyArray_DATA(capi_cs_as_array));

    /* Processing variable cp */
    cp_Dims[0]=10;
    capi_cp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.crtovrlp: failed to create array from the 4th argument `cp`";
    capi_cp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,cp_Dims,cp_Rank,  capi_cp_intent,cp_capi,capi_errmess);
    if (capi_cp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        cp = (double *)(PyArray_DATA(capi_cp_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(rxyz, 1); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"fingerprint.crtovrlp() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rxyz, 1) == nat,"shape(rxyz, 1) == nat","1st keyword nat","crtovrlp:nat=%d",nat) {
    /* Processing variable ovrlp */
    ovrlp_Dims[0]=3 * nat * np + nat * ns,ovrlp_Dims[1]=3 * nat * np + nat * ns;
    capi_ovrlp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.crtovrlp: failed to create array from the 7th argument `ovrlp`";
    capi_ovrlp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ovrlp_Dims,ovrlp_Rank,  capi_ovrlp_intent,ovrlp_capi,capi_errmess);
    if (capi_ovrlp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ovrlp = (double *)(PyArray_DATA(capi_ovrlp_as_array));

    CHECKARRAY(shape(ovrlp, 0) == 3 * nat * np + nat * ns,"shape(ovrlp, 0) == 3 * nat * np + nat * ns","7th argument ovrlp") {
    CHECKARRAY(shape(ovrlp, 0) == 3 * nat * np + nat * ns,"shape(ovrlp, 0) == 3 * nat * np + nat * ns","7th argument ovrlp") {
    /* Processing variable alpha */
    alpha_Dims[0]=nat;
    capi_alpha_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.crtovrlp: failed to create array from the 2nd argument `alpha`";
    capi_alpha_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,alpha_Dims,alpha_Rank,  capi_alpha_intent,alpha_capi,capi_errmess);
    if (capi_alpha_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        alpha = (double *)(PyArray_DATA(capi_alpha_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nat,rxyz,alpha,cs,cp,&ns,&np,ovrlp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_alpha_as_array!=alpha_capi) {
        Py_XDECREF(capi_alpha_as_array); }
    }  /* if (capi_alpha_as_array == NULL) ... else of alpha */
    /* End of cleaning variable alpha */
    } /*CHECKARRAY(shape(ovrlp, 0) == 3 * nat * np + nat * ns)*/
    } /*CHECKARRAY(shape(ovrlp, 0) == 3 * nat * np + nat * ns)*/
    if((PyObject *)capi_ovrlp_as_array!=ovrlp_capi) {
        Py_XDECREF(capi_ovrlp_as_array); }
    }  /* if (capi_ovrlp_as_array == NULL) ... else of ovrlp */
    /* End of cleaning variable ovrlp */
    } /*CHECKSCALAR(shape(rxyz, 1) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_cp_as_array!=cp_capi) {
        Py_XDECREF(capi_cp_as_array); }
    }  /* if (capi_cp_as_array == NULL) ... else of cp */
    /* End of cleaning variable cp */
    if((PyObject *)capi_cs_as_array!=cs_capi) {
        Py_XDECREF(capi_cs_as_array); }
    }  /* if (capi_cs_as_array == NULL) ... else of cs */
    /* End of cleaning variable cs */
    if((PyObject *)capi_rxyz_as_array!=rxyz_capi) {
        Py_XDECREF(capi_rxyz_as_array); }
    }  /* if (capi_rxyz_as_array == NULL) ... else of rxyz */
    /* End of cleaning variable rxyz */
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of crtovrlp ******************************/

/********************************** multamp **********************************/
static char doc_f2py_rout_fingerprint_multamp[] = "\
multamp(ovrlp,amplitude,ns,np,ovrla,[nat,norb])\n\nWrapper for ``multamp``.\
\n\nParameters\n----------\n"
"ovrlp : input rank-2 array('d') with bounds (norb,norb)\n"
"amplitude : input rank-1 array('d') with bounds (nat)\n"
"ns : input int\n"
"np : input int\n"
"ovrla : input rank-2 array('d') with bounds (norb,norb)\n"
"\nOther Parameters\n----------------\n"
"nat : input int, optional\n    Default: shape(amplitude, 0)\n"
"norb : input int, optional\n    Default: shape(ovrlp, 0)";
/* extern void F_FUNC(multamp,MULTAMP)(int*,double*,double*,int*,int*,int*,double*); */
static PyObject *f2py_rout_fingerprint_multamp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,int*,int*,int*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int nat = 0;
    PyObject *nat_capi = Py_None;
    double *ovrlp = NULL;
    npy_intp ovrlp_Dims[2] = {-1, -1};
    const int ovrlp_Rank = 2;
    PyArrayObject *capi_ovrlp_as_array = NULL;
    int capi_ovrlp_intent = 0;
    PyObject *ovrlp_capi = Py_None;
    double *amplitude = NULL;
    npy_intp amplitude_Dims[1] = {-1};
    const int amplitude_Rank = 1;
    PyArrayObject *capi_amplitude_as_array = NULL;
    int capi_amplitude_intent = 0;
    PyObject *amplitude_capi = Py_None;
    int norb = 0;
    PyObject *norb_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double *ovrla = NULL;
    npy_intp ovrla_Dims[2] = {-1, -1};
    const int ovrla_Rank = 2;
    PyArrayObject *capi_ovrla_as_array = NULL;
    int capi_ovrla_intent = 0;
    PyObject *ovrla_capi = Py_None;
    static char *capi_kwlist[] = {"ovrlp","amplitude","ns","np","ovrla","nat","norb",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|OO:fingerprint.multamp",\
        capi_kwlist,&ovrlp_capi,&amplitude_capi,&ns_capi,&np_capi,&ovrla_capi,&nat_capi,&norb_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"fingerprint.multamp() 3rd argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
        f2py_success = int_from_pyobj(&np,np_capi,"fingerprint.multamp() 4th argument (np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable amplitude */
    ;
    capi_amplitude_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.multamp: failed to create array from the 2nd argument `amplitude`";
    capi_amplitude_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,amplitude_Dims,amplitude_Rank,  capi_amplitude_intent,amplitude_capi,capi_errmess);
    if (capi_amplitude_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        amplitude = (double *)(PyArray_DATA(capi_amplitude_as_array));

    /* Processing variable ovrlp */
    ;
    capi_ovrlp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.multamp: failed to create array from the 1st argument `ovrlp`";
    capi_ovrlp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ovrlp_Dims,ovrlp_Rank,  capi_ovrlp_intent,ovrlp_capi,capi_errmess);
    if (capi_ovrlp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ovrlp = (double *)(PyArray_DATA(capi_ovrlp_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(amplitude, 0); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"fingerprint.multamp() 1st keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(amplitude, 0) == nat,"shape(amplitude, 0) == nat","1st keyword nat","multamp:nat=%d",nat) {
    /* Processing variable norb */
    if (norb_capi == Py_None) norb = shape(ovrlp, 0); else
        f2py_success = int_from_pyobj(&norb,norb_capi,"fingerprint.multamp() 2nd keyword (norb) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(ovrlp, 0) == norb,"shape(ovrlp, 0) == norb","2nd keyword norb","multamp:norb=%d",norb) {
    /* Processing variable ovrla */
    ovrla_Dims[0]=norb,ovrla_Dims[1]=norb;
    capi_ovrla_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.multamp: failed to create array from the 5th argument `ovrla`";
    capi_ovrla_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ovrla_Dims,ovrla_Rank,  capi_ovrla_intent,ovrla_capi,capi_errmess);
    if (capi_ovrla_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ovrla = (double *)(PyArray_DATA(capi_ovrla_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&nat,ovrlp,amplitude,&norb,&ns,&np,ovrla);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_ovrla_as_array!=ovrla_capi) {
        Py_XDECREF(capi_ovrla_as_array); }
    }  /* if (capi_ovrla_as_array == NULL) ... else of ovrla */
    /* End of cleaning variable ovrla */
    } /*CHECKSCALAR(shape(ovrlp, 0) == norb)*/
    } /*if (f2py_success) of norb*/
    /* End of cleaning variable norb */
    } /*CHECKSCALAR(shape(amplitude, 0) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_ovrlp_as_array!=ovrlp_capi) {
        Py_XDECREF(capi_ovrlp_as_array); }
    }  /* if (capi_ovrlp_as_array == NULL) ... else of ovrlp */
    /* End of cleaning variable ovrlp */
    if((PyObject *)capi_amplitude_as_array!=amplitude_capi) {
        Py_XDECREF(capi_amplitude_as_array); }
    }  /* if (capi_amplitude_as_array == NULL) ... else of amplitude */
    /* End of cleaning variable amplitude */
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of multamp *******************************/

/***************************** diagonalizeMatrix *****************************/
static char doc_f2py_rout_fingerprint_diagonalizeMatrix[] = "\
diagonalizeMatrix(aa,eval,[n])\n\nWrapper for ``diagonalizeMatrix``.\
\n\nParameters\n----------\n"
"aa : input rank-2 array('d') with bounds (n,n)\n"
"eval : input rank-1 array('d') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: shape(aa, 0)";
/* extern void F_FUNC(diagonalizeMatrix,DIAGONALIZEMATRIX)(int*,double*,double*); */
static PyObject *f2py_rout_fingerprint_diagonalizeMatrix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int n = 0;
    PyObject *n_capi = Py_None;
    double *aa = NULL;
    npy_intp aa_Dims[2] = {-1, -1};
    const int aa_Rank = 2;
    PyArrayObject *capi_aa_as_array = NULL;
    int capi_aa_intent = 0;
    PyObject *aa_capi = Py_None;
    double *eval = NULL;
    npy_intp eval_Dims[1] = {-1};
    const int eval_Rank = 1;
    PyArrayObject *capi_eval_as_array = NULL;
    int capi_eval_intent = 0;
    PyObject *eval_capi = Py_None;
    static char *capi_kwlist[] = {"aa","eval","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:fingerprint.diagonalizeMatrix",\
        capi_kwlist,&aa_capi,&eval_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable aa */
    ;
    capi_aa_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.diagonalizeMatrix: failed to create array from the 1st argument `aa`";
    capi_aa_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,aa_Dims,aa_Rank,  capi_aa_intent,aa_capi,capi_errmess);
    if (capi_aa_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        aa = (double *)(PyArray_DATA(capi_aa_as_array));

    /* Processing variable n */
    if (n_capi == Py_None) n = shape(aa, 0); else
        f2py_success = int_from_pyobj(&n,n_capi,"fingerprint.diagonalizeMatrix() 1st keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(aa, 0) == n,"shape(aa, 0) == n","1st keyword n","diagonalizeMatrix:n=%d",n) {
    /* Processing variable eval */
    eval_Dims[0]=n;
    capi_eval_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.diagonalizeMatrix: failed to create array from the 2nd argument `eval`";
    capi_eval_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,eval_Dims,eval_Rank,  capi_eval_intent,eval_capi,capi_errmess);
    if (capi_eval_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        eval = (double *)(PyArray_DATA(capi_eval_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&n,aa,eval);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_eval_as_array!=eval_capi) {
        Py_XDECREF(capi_eval_as_array); }
    }  /* if (capi_eval_as_array == NULL) ... else of eval */
    /* End of cleaning variable eval */
    } /*CHECKSCALAR(shape(aa, 0) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    if((PyObject *)capi_aa_as_array!=aa_capi) {
        Py_XDECREF(capi_aa_as_array); }
    }  /* if (capi_aa_as_array == NULL) ... else of aa */
    /* End of cleaning variable aa */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************** end of diagonalizeMatrix **************************/

/********************************** sym2rcov **********************************/
static char doc_f2py_rout_fingerprint_sym2rcov[] = "\
sym2rcov(sym,rcov)\n\nWrapper for ``sym2rcov``.\
\n\nParameters\n----------\n"
"sym : input string(len=2)\n"
"rcov : input float";
/* extern void F_FUNC(sym2rcov,SYM2RCOV)(string,double*,size_t); */
static PyObject *f2py_rout_fingerprint_sym2rcov(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,double*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string sym = NULL;
    int slen(sym);
    PyObject *sym_capi = Py_None;
    double rcov = 0;
    PyObject *rcov_capi = Py_None;
    static char *capi_kwlist[] = {"sym","rcov",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:fingerprint.sym2rcov",\
        capi_kwlist,&sym_capi,&rcov_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable rcov */
        f2py_success = double_from_pyobj(&rcov,rcov_capi,"fingerprint.sym2rcov() 2nd argument (rcov) can't be converted to double");
    if (f2py_success) {
    /* Processing variable sym */
    slen(sym) = 2;
    f2py_success = string_from_pyobj(&sym,&slen(sym),"",sym_capi,"string_from_pyobj failed in converting 1st argument`sym' of fingerprint.sym2rcov to C string");
    if (f2py_success) {
        STRINGPADN(sym, slen(sym), '\0', ' ');
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(sym,&rcov,slen(sym));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        STRINGFREE(sym);
    }  /*if (f2py_success) of sym*/
    /* End of cleaning variable sym */
    } /*if (f2py_success) of rcov*/
    /* End of cleaning variable rcov */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of sym2rcov ******************************/

/******************************** xyz2ovrlpdr ********************************/
static char doc_f2py_rout_fingerprint_xyz2ovrlpdr[] = "\
xyz2ovrlpdr(rxyz,rcov,amplitude,deramplitude,lat,xl,yl,zl,ns,np,dovrlpdr,ovrlp,[norb,nat])\n\nWrapper for ``xyz2ovrlpdr``.\
\n\nParameters\n----------\n"
"rxyz : input rank-2 array('d') with bounds (3,nat)\n"
"rcov : input rank-1 array('d') with bounds (nat)\n"
"amplitude : input rank-1 array('d') with bounds (nat)\n"
"deramplitude : input rank-1 array('d') with bounds (nat)\n"
"lat : input int\n"
"xl : input float\n"
"yl : input float\n"
"zl : input float\n"
"ns : input int\n"
"np : input int\n"
"dovrlpdr : input rank-4 array('d') with bounds (norb,norb,3,nat)\n"
"ovrlp : input rank-2 array('d') with bounds (norb,norb)\n"
"\nOther Parameters\n----------------\n"
"norb : input int, optional\n    Default: shape(dovrlpdr, 0)\n"
"nat : input int, optional\n    Default: shape(rxyz, 1)";
/* extern void F_FUNC(xyz2ovrlpdr,XYZ2OVRLPDR)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,int*,int*,double*,double*); */
static PyObject *f2py_rout_fingerprint_xyz2ovrlpdr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,double*,double*,int*,double*,double*,double*,int*,int*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int norb = 0;
    PyObject *norb_capi = Py_None;
    int nat = 0;
    PyObject *nat_capi = Py_None;
    double *rxyz = NULL;
    npy_intp rxyz_Dims[2] = {-1, -1};
    const int rxyz_Rank = 2;
    PyArrayObject *capi_rxyz_as_array = NULL;
    int capi_rxyz_intent = 0;
    PyObject *rxyz_capi = Py_None;
    double *rcov = NULL;
    npy_intp rcov_Dims[1] = {-1};
    const int rcov_Rank = 1;
    PyArrayObject *capi_rcov_as_array = NULL;
    int capi_rcov_intent = 0;
    PyObject *rcov_capi = Py_None;
    double *amplitude = NULL;
    npy_intp amplitude_Dims[1] = {-1};
    const int amplitude_Rank = 1;
    PyArrayObject *capi_amplitude_as_array = NULL;
    int capi_amplitude_intent = 0;
    PyObject *amplitude_capi = Py_None;
    double *deramplitude = NULL;
    npy_intp deramplitude_Dims[1] = {-1};
    const int deramplitude_Rank = 1;
    PyArrayObject *capi_deramplitude_as_array = NULL;
    int capi_deramplitude_intent = 0;
    PyObject *deramplitude_capi = Py_None;
    int lat = 0;
    PyObject *lat_capi = Py_None;
    double xl = 0;
    PyObject *xl_capi = Py_None;
    double yl = 0;
    PyObject *yl_capi = Py_None;
    double zl = 0;
    PyObject *zl_capi = Py_None;
    int ns = 0;
    PyObject *ns_capi = Py_None;
    int np = 0;
    PyObject *np_capi = Py_None;
    double *dovrlpdr = NULL;
    npy_intp dovrlpdr_Dims[4] = {-1, -1, -1, -1};
    const int dovrlpdr_Rank = 4;
    PyArrayObject *capi_dovrlpdr_as_array = NULL;
    int capi_dovrlpdr_intent = 0;
    PyObject *dovrlpdr_capi = Py_None;
    double *ovrlp = NULL;
    npy_intp ovrlp_Dims[2] = {-1, -1};
    const int ovrlp_Rank = 2;
    PyArrayObject *capi_ovrlp_as_array = NULL;
    int capi_ovrlp_intent = 0;
    PyObject *ovrlp_capi = Py_None;
    static char *capi_kwlist[] = {"rxyz","rcov","amplitude","deramplitude","lat","xl","yl","zl","ns","np","dovrlpdr","ovrlp","norb","nat",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOO|OO:fingerprint.xyz2ovrlpdr",\
        capi_kwlist,&rxyz_capi,&rcov_capi,&amplitude_capi,&deramplitude_capi,&lat_capi,&xl_capi,&yl_capi,&zl_capi,&ns_capi,&np_capi,&dovrlpdr_capi,&ovrlp_capi,&norb_capi,&nat_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable ns */
        f2py_success = int_from_pyobj(&ns,ns_capi,"fingerprint.xyz2ovrlpdr() 9th argument (ns) can't be converted to int");
    if (f2py_success) {
    /* Processing variable np */
        f2py_success = int_from_pyobj(&np,np_capi,"fingerprint.xyz2ovrlpdr() 10th argument (np) can't be converted to int");
    if (f2py_success) {
    /* Processing variable lat */
        f2py_success = int_from_pyobj(&lat,lat_capi,"fingerprint.xyz2ovrlpdr() 5th argument (lat) can't be converted to int");
    if (f2py_success) {
    /* Processing variable xl */
        f2py_success = double_from_pyobj(&xl,xl_capi,"fingerprint.xyz2ovrlpdr() 6th argument (xl) can't be converted to double");
    if (f2py_success) {
    /* Processing variable yl */
        f2py_success = double_from_pyobj(&yl,yl_capi,"fingerprint.xyz2ovrlpdr() 7th argument (yl) can't be converted to double");
    if (f2py_success) {
    /* Processing variable zl */
        f2py_success = double_from_pyobj(&zl,zl_capi,"fingerprint.xyz2ovrlpdr() 8th argument (zl) can't be converted to double");
    if (f2py_success) {
    /* Processing variable rxyz */
    rxyz_Dims[0]=3;
    capi_rxyz_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 1st argument `rxyz`";
    capi_rxyz_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rxyz_Dims,rxyz_Rank,  capi_rxyz_intent,rxyz_capi,capi_errmess);
    if (capi_rxyz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rxyz = (double *)(PyArray_DATA(capi_rxyz_as_array));

    /* Processing variable nat */
    if (nat_capi == Py_None) nat = shape(rxyz, 1); else
        f2py_success = int_from_pyobj(&nat,nat_capi,"fingerprint.xyz2ovrlpdr() 2nd keyword (nat) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(rxyz, 1) == nat,"shape(rxyz, 1) == nat","2nd keyword nat","xyz2ovrlpdr:nat=%d",nat) {
    /* Processing variable rcov */
    rcov_Dims[0]=nat;
    capi_rcov_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 2nd argument `rcov`";
    capi_rcov_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,rcov_Dims,rcov_Rank,  capi_rcov_intent,rcov_capi,capi_errmess);
    if (capi_rcov_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rcov = (double *)(PyArray_DATA(capi_rcov_as_array));

    /* Processing variable amplitude */
    amplitude_Dims[0]=nat;
    capi_amplitude_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 3rd argument `amplitude`";
    capi_amplitude_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,amplitude_Dims,amplitude_Rank,  capi_amplitude_intent,amplitude_capi,capi_errmess);
    if (capi_amplitude_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        amplitude = (double *)(PyArray_DATA(capi_amplitude_as_array));

    /* Processing variable deramplitude */
    deramplitude_Dims[0]=nat;
    capi_deramplitude_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 4th argument `deramplitude`";
    capi_deramplitude_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,deramplitude_Dims,deramplitude_Rank,  capi_deramplitude_intent,deramplitude_capi,capi_errmess);
    if (capi_deramplitude_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        deramplitude = (double *)(PyArray_DATA(capi_deramplitude_as_array));

    /* Processing variable dovrlpdr */
    dovrlpdr_Dims[2]=3,dovrlpdr_Dims[3]=nat;
    capi_dovrlpdr_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 11st argument `dovrlpdr`";
    capi_dovrlpdr_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,dovrlpdr_Dims,dovrlpdr_Rank,  capi_dovrlpdr_intent,dovrlpdr_capi,capi_errmess);
    if (capi_dovrlpdr_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        dovrlpdr = (double *)(PyArray_DATA(capi_dovrlpdr_as_array));

    /* Processing variable norb */
    if (norb_capi == Py_None) norb = shape(dovrlpdr, 0); else
        f2py_success = int_from_pyobj(&norb,norb_capi,"fingerprint.xyz2ovrlpdr() 1st keyword (norb) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(dovrlpdr, 0) == norb,"shape(dovrlpdr, 0) == norb","1st keyword norb","xyz2ovrlpdr:norb=%d",norb) {
    /* Processing variable ovrlp */
    ovrlp_Dims[0]=norb,ovrlp_Dims[1]=norb;
    capi_ovrlp_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fingerprint.fingerprint.xyz2ovrlpdr: failed to create array from the 12nd argument `ovrlp`";
    capi_ovrlp_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ovrlp_Dims,ovrlp_Rank,  capi_ovrlp_intent,ovrlp_capi,capi_errmess);
    if (capi_ovrlp_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fingerprint_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ovrlp = (double *)(PyArray_DATA(capi_ovrlp_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&norb,&nat,rxyz,rcov,amplitude,deramplitude,&lat,&xl,&yl,&zl,&ns,&np,dovrlpdr,ovrlp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_ovrlp_as_array!=ovrlp_capi) {
        Py_XDECREF(capi_ovrlp_as_array); }
    }  /* if (capi_ovrlp_as_array == NULL) ... else of ovrlp */
    /* End of cleaning variable ovrlp */
    } /*CHECKSCALAR(shape(dovrlpdr, 0) == norb)*/
    } /*if (f2py_success) of norb*/
    /* End of cleaning variable norb */
    if((PyObject *)capi_dovrlpdr_as_array!=dovrlpdr_capi) {
        Py_XDECREF(capi_dovrlpdr_as_array); }
    }  /* if (capi_dovrlpdr_as_array == NULL) ... else of dovrlpdr */
    /* End of cleaning variable dovrlpdr */
    if((PyObject *)capi_deramplitude_as_array!=deramplitude_capi) {
        Py_XDECREF(capi_deramplitude_as_array); }
    }  /* if (capi_deramplitude_as_array == NULL) ... else of deramplitude */
    /* End of cleaning variable deramplitude */
    if((PyObject *)capi_amplitude_as_array!=amplitude_capi) {
        Py_XDECREF(capi_amplitude_as_array); }
    }  /* if (capi_amplitude_as_array == NULL) ... else of amplitude */
    /* End of cleaning variable amplitude */
    if((PyObject *)capi_rcov_as_array!=rcov_capi) {
        Py_XDECREF(capi_rcov_as_array); }
    }  /* if (capi_rcov_as_array == NULL) ... else of rcov */
    /* End of cleaning variable rcov */
    } /*CHECKSCALAR(shape(rxyz, 1) == nat)*/
    } /*if (f2py_success) of nat*/
    /* End of cleaning variable nat */
    if((PyObject *)capi_rxyz_as_array!=rxyz_capi) {
        Py_XDECREF(capi_rxyz_as_array); }
    }  /* if (capi_rxyz_as_array == NULL) ... else of rxyz */
    /* End of cleaning variable rxyz */
    } /*if (f2py_success) of zl*/
    /* End of cleaning variable zl */
    } /*if (f2py_success) of yl*/
    /* End of cleaning variable yl */
    } /*if (f2py_success) of xl*/
    /* End of cleaning variable xl */
    } /*if (f2py_success) of lat*/
    /* End of cleaning variable lat */
    } /*if (f2py_success) of np*/
    /* End of cleaning variable np */
    } /*if (f2py_success) of ns*/
    /* End of cleaning variable ns */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of xyz2ovrlpdr *****************************/

/************************************ cite ************************************/
static char doc_f2py_rout_fingerprint_cite[] = "\
cite()\n\nWrapper for ``cite``.\
\n";
/* extern void F_FUNC(cite,CITE)(void); */
static PyObject *f2py_rout_fingerprint_cite(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:fingerprint.cite",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of cite ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"fingerprint_and_derivatives",-1,{{-1}},0,0,(char *)  F_FUNC_US(fingerprint_and_derivatives,FINGERPRINT_AND_DERIVATIVES),  (f2py_init_func)f2py_rout_fingerprint_fingerprint_and_derivatives,doc_f2py_rout_fingerprint_fingerprint_and_derivatives},
    {"atoms_sphere",-1,{{-1}},0,0,(char *)  F_FUNC_US(atoms_sphere,ATOMS_SPHERE),  (f2py_init_func)f2py_rout_fingerprint_atoms_sphere,doc_f2py_rout_fingerprint_atoms_sphere},
    {"crtovrlp",-1,{{-1}},0,0,(char *)  F_FUNC(crtovrlp,CRTOVRLP),  (f2py_init_func)f2py_rout_fingerprint_crtovrlp,doc_f2py_rout_fingerprint_crtovrlp},
    {"multamp",-1,{{-1}},0,0,(char *)  F_FUNC(multamp,MULTAMP),  (f2py_init_func)f2py_rout_fingerprint_multamp,doc_f2py_rout_fingerprint_multamp},
    {"diagonalizeMatrix",-1,{{-1}},0,0,(char *)  F_FUNC(diagonalizeMatrix,DIAGONALIZEMATRIX),  (f2py_init_func)f2py_rout_fingerprint_diagonalizeMatrix,doc_f2py_rout_fingerprint_diagonalizeMatrix},
    {"sym2rcov",-1,{{-1}},0,0,(char *)  F_FUNC(sym2rcov,SYM2RCOV),  (f2py_init_func)f2py_rout_fingerprint_sym2rcov,doc_f2py_rout_fingerprint_sym2rcov},
    {"xyz2ovrlpdr",-1,{{-1}},0,0,(char *)  F_FUNC(xyz2ovrlpdr,XYZ2OVRLPDR),  (f2py_init_func)f2py_rout_fingerprint_xyz2ovrlpdr,doc_f2py_rout_fingerprint_xyz2ovrlpdr},
    {"cite",-1,{{-1}},0,0,(char *)  F_FUNC(cite,CITE),  (f2py_init_func)f2py_rout_fingerprint_cite,doc_f2py_rout_fingerprint_cite},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "fingerprint",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_fingerprint(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = fingerprint_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module fingerprint (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'fingerprint' is auto-generated with f2py (version:1.24.3).\nFunctions:\n"
"    fingerprint_and_derivatives(nat_sphere_max,ns,np,width_cutoff,alat,rxyz,rcov,fp,dfp,nat=shape(rxyz, 1))\n"
"    atoms_sphere(width_cutoff,nex_cutoff,lat,llat,ixyzmax,nat_sphere,alat,rxyz,rxyz_sphere,rcov,rcov_sphere,indat,amplitude,deramplitude,nat=shape(rxyz, 1),natx_sphere=shape(rxyz_sphere, 1))\n"
"    crtovrlp(rxyz,alpha,cs,cp,ns,np,ovrlp,nat=shape(rxyz, 1))\n"
"    multamp(ovrlp,amplitude,ns,np,ovrla,nat=shape(amplitude, 0),norb=shape(ovrlp, 0))\n"
"    diagonalizeMatrix(aa,eval,n=shape(aa, 0))\n"
"    sym2rcov(sym,rcov)\n"
"    xyz2ovrlpdr(rxyz,rcov,amplitude,deramplitude,lat,xl,yl,zl,ns,np,dovrlpdr,ovrlp,norb=shape(dovrlpdr, 0),nat=shape(rxyz, 1))\n"
"    cite()\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    fingerprint_error = PyErr_NewException ("fingerprint.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_fingerprint_error", fingerprint_error);
    Py_DECREF(fingerprint_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }








/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"fingerprint");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
